#!/bin/sh
#
# pre-commit - pre-commit hook for Tryton module
#

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    AGAINST=HEAD
else
    # Initial commit: diff against an empty tree object
    AGAINST=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr
exec 1>&2

# Check for whitespace errors
git diff-index --check --cached ${AGAINST} --
[ $? != 0 ] && exit 1

# Check to ensure python files comply with pep8
if git diff --cached --name-only --diff-filter=ACM | grep -q '.*\.py'; then
    flake8 $( \
        git diff --cached --name-only --diff-filter=ACM "${AGAINST}" | \
        grep '.*\.py' )
    [ $? != 0 ] && exit 1
fi

# Check xml files to ensure that they are valid
if git diff --cached --name-only --diff-filter=ACM | grep -q '.*\.xml'; then
    xmllint --noout $( \
        git diff --cached --name-only --diff-filter=ACM "${AGAINST}" | \
        grep '.*\.xml' )
    [ $? != 0 ] && exit 1
fi

# Check for TODOs
if git diff --cached --name-only --diff-filter=ACM | grep -q -v 'cookiecutter'; then
    grep -i todo $( \
        git diff --cached --name-only --diff-filter=ACM "${AGAINST}" | \
        grep -v 'cookiecutter' )
    [ $? != 1 ] && exit 1
fi

exit 0
